# https://docs.travis-ci.com/user/reference/overview/
dist: focal
arch: amd64

# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "pypy3"
cache: pip

env:
  - PILLOW=8.*
  - PILLOW=9.*
  - PILLOW=10.*
install:
  - pip install pytest Pillow==$PILLOW
  - pip install -e .
script:
  - pytest tests/
jobs:
  allow_failures:
    - python: "pypy3"
